### ISSUE TITLE
tryTake(long, TimeUnit) doesn't behave like expected – not returning NULL after waiting period

### ISSUE THREAD

**Issue by sdoeringNew** [vibur/vibur-object-pool#3]
If the minimum size for the pool is zero the method tryTake(long, TimeUnit) will create a new pooled "Object". If this creation got stuck the method will not return anything indefinitely.

This is the opposite of the JavaDoc: "@return an object taken from the object pool or {@code null} if the specified timeout expires or if it was interrupted while waiting".
Either the JavaDoc should be edited or the process of object creation should be limited to the waiting period, too.

**Comment by simeonmalchev** [comment]
Yes, the JavaDoc is not precise enough. It should say something along the lines that the method can wait maximum the given timeout _plus_ the object creation time, if no valid object is available in the pool. I'll fix the JavaDoc in the next release.

However, for the object creation to get stuck and not return indefinitely, it is quite strange. There should be some timeouts controlling the object creation that you are able to tune. For example, if the objects are one or another form of network sockets, there are login and read timeouts that can be set in order to guarantee the creation will finish within a desired timeout.

**Comment by simeonmalchev** [comment]
Javadoc was fixed in release 10.0 which was just sent to Maven Central, should be available there in a few  hours.
